@startuml

actor ユーザ as user
participant アプリケーション as app
participant FileList as fs
participant CropView as cv
participant TilePreview as tp

user -> app :アプリの起動;

user -> app :画像ファイルをドラッグアンドドロップ;
app -> fs :画像ファイルパスリストのstateを更新;
app -> user :画面を更新表示;

user -> app :画像ファイルを選択;
app -> fs :選択画像を更新;
app -> cv :画像を描画;
app -> user :画像を描画;

app -> user :アプリの終了;

@enduml
